version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: golang_microservice_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: golang_microservice_api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: mydatabase
      JWT_SECRET: mysecretkey
    ports:
      - "8080:8080"

volumes:
  pgdata:
